// genre+mood → canonical ProfileConfigs key.
// Aliases collapse intra-genre near-synonyms only. Cross-genre combos resolve directly as genre+mood ProfileConfigs keys.
// Combos NOT listed here resolve directly as `genre+mood` keys in ProfileConfigs (or fall back to bare genre).
export const GenreMoodAliasMap: Record<string, string> = {
  // ── rock ─────────────────────────────────────────────────────────────────
  // emotional group
  'rock+love':              'rock+romantic',
  'rock+ballad':            'rock+emotional',
  'rock+melancholic':       'rock+emotional',
  // epic group
  'rock+dramatic':          'rock+epic',
  'rock+powerful':          'rock+epic',
  'rock+trailer':           'rock+epic',
  'rock+adventure':         'rock+epic',
  'rock+action':            'rock+epic',
  'rock+cinematic':         'rock+epic',
  // dark group
  'rock+heavy':             'rock+dark',
  'rock+grim':              'rock+dark',
  'rock+drama':             'rock+dark',
  // upbeat group
  'rock+summer':            'rock+upbeat',
  'rock+groovy':            'rock+upbeat',
  'rock+fun':               'rock+upbeat',
  'rock+dance':             'rock+upbeat',
  'rock+uplifting':         'rock+epic',
  'rock+inspiring':         'rock+epic',
  'rock+energetic':         'rock+epic',
  'rock+fast':              'rock+upbeat',
  'rock+positive':          'rock+upbeat',
  'rock+motivational':      'rock+upbeat',
  'rock+hopeful':           'rock+upbeat',
  'rock+funny':             'rock+upbeat',
  'rock+happy':             'rock+upbeat',
  'rock+party':             'rock+upbeat',
  'rock+advertising':       'rock+upbeat',
  'rock+commercial':        'rock+upbeat',
  'rock+children':          'rock+upbeat',
  'rock+holiday':           'rock+upbeat',
  'rock+retro':             'rock+upbeat',
  // epic group additions
  'rock+game':              'rock+epic',
  'rock+sport':             'rock+epic',
  'rock+documentary':       'rock+epic',
  // calm group
  'rock+meditative':        'rock+calm',
  'rock+nature':            'rock+calm',
  'rock+space':             'rock+calm',
  'rock+dream':             'rock+calm',
  'rock+film':              'rock+calm',
  'rock+movie':             'rock+calm',
  'rock+travel':            'rock+calm',
  'rock+soft':              'rock+calm',
  'rock+slow':              'rock+calm',
  'rock+background':        'rock+calm',
  'rock+soundscape':        'rock+calm',
  'rock+relaxing':          'rock+calm',
  'rock+cool':              'rock+calm',
  'rock+corporate':         'rock+calm',
  // emotional group additions
  'rock+sad':               'rock+emotional',

  // ── pop ──────────────────────────────────────────────────────────────────
  // emotional group
  'pop+love':               'pop+romantic',
  'pop+ballad':             'pop+emotional',
  'pop+melancholic':        'pop+emotional',
  // epic group
  'pop+dramatic':           'pop+epic',
  'pop+powerful':           'pop+epic',
  'pop+trailer':            'pop+epic',
  'pop+adventure':          'pop+epic',
  'pop+action':             'pop+epic',
  'pop+cinematic':          'pop+epic',
  // dark group
  'pop+heavy':              'pop+dark',
  'pop+grim':               'pop+dark',
  'pop+drama':              'pop+dark',
  // upbeat group
  'pop+summer':             'pop+upbeat',
  'pop+groovy':             'pop+upbeat',
  'pop+fun':                'pop+upbeat',
  'pop+dance':              'pop+upbeat',
  'pop+uplifting':          'pop+upbeat',
  'pop+inspiring':          'pop+upbeat',
  'pop+energetic':          'pop+upbeat',
  'pop+fast':               'pop+upbeat',
  'pop+positive':           'pop+upbeat',
  'pop+motivational':       'pop+upbeat',
  'pop+hopeful':            'pop+upbeat',
  'pop+funny':              'pop+upbeat',
  'pop+party':              'pop+upbeat',
  'pop+advertising':        'pop+upbeat',
  'pop+commercial':         'pop+upbeat',
  'pop+children':           'pop+upbeat',
  'pop+holiday':            'pop+upbeat',
  'pop+retro':              'pop+upbeat',
  // epic group additions
  'pop+game':               'pop+epic',
  'pop+sport':              'pop+epic',
  'pop+documentary':        'pop+epic',
  // calm group
  'pop+meditative':         'pop+calm',
  'pop+nature':             'pop+calm',
  'pop+space':              'pop+calm',
  'pop+dream':              'pop+calm',
  'pop+film':               'pop+calm',
  'pop+movie':              'pop+calm',
  'pop+travel':             'pop+calm',
  'pop+soft':               'pop+calm',
  'pop+slow':               'pop+calm',
  'pop+background':         'pop+calm',
  'pop+soundscape':         'pop+calm',
  'pop+relaxing':           'pop+calm',
  'pop+cool':               'pop+calm',
  'pop+corporate':          'pop+calm',
  // emotional group additions
  'pop+sad':                'pop+emotional',

  // ── electronic ───────────────────────────────────────────────────────────
  // emotional group
  'electronic+love':        'electronic+romantic',
  'electronic+ballad':      'electronic+emotional',
  'electronic+melancholic': 'electronic+emotional',
  // epic group
  'electronic+dramatic':    'electronic+epic',
  'electronic+powerful':    'electronic+epic',
  'electronic+trailer':     'electronic+epic',
  'electronic+adventure':   'electronic+epic',
  'electronic+action':      'electronic+epic',
  'electronic+cinematic':   'electronic+epic',
  // dark group
  'electronic+heavy':       'electronic+dark',
  'electronic+grim':        'electronic+dark',
  'electronic+deep':        'electronic+dark',
  'electronic+drama':       'electronic+dark',
  // upbeat group
  'electronic+summer':      'electronic+upbeat',
  'electronic+fun':         'electronic+upbeat',
  'electronic+uplifting':   'electronic+upbeat',
  'electronic+inspiring':   'electronic+upbeat',
  'electronic+energetic':   'electronic+epic',
  'electronic+fast':        'electronic+upbeat',
  'electronic+positive':    'electronic+upbeat',
  'electronic+motivational':'electronic+upbeat',
  'electronic+hopeful':     'electronic+upbeat',
  'electronic+funny':       'electronic+upbeat',
  'electronic+happy':       'electronic+upbeat',
  'electronic+party':       'electronic+upbeat',
  'electronic+advertising': 'electronic+upbeat',
  'electronic+commercial':  'electronic+upbeat',
  'electronic+children':    'electronic+upbeat',
  'electronic+holiday':     'electronic+upbeat',
  'electronic+retro':       'electronic+upbeat',
  // epic group additions
  'electronic+game':        'electronic+epic',
  'electronic+sport':       'electronic+epic',
  'electronic+documentary': 'electronic+epic',
  // calm group
  'electronic+meditative':  'electronic+calm',
  'electronic+nature':      'electronic+calm',
  'electronic+space':       'electronic+calm',
  'electronic+dream':       'electronic+calm',
  'electronic+film':        'electronic+calm',
  'electronic+movie':       'electronic+calm',
  'electronic+travel':      'electronic+calm',
  'electronic+soft':        'electronic+calm',
  'electronic+slow':        'electronic+calm',
  'electronic+background':  'electronic+calm',
  'electronic+soundscape':  'electronic+calm',
  'electronic+relaxing':    'electronic+calm',
  'electronic+cool':        'electronic+calm',
  'electronic+corporate':   'electronic+calm',
  // emotional group additions
  'electronic+sad':         'electronic+emotional',

  // ── hiphop ───────────────────────────────────────────────────────────────
  // emotional group
  'hiphop+love':            'hiphop+romantic',
  'hiphop+ballad':          'hiphop+emotional',
  'hiphop+melancholic':     'hiphop+emotional',
  // epic group
  'hiphop+dramatic':        'hiphop+epic',
  'hiphop+powerful':        'hiphop+epic',
  'hiphop+trailer':         'hiphop+epic',
  'hiphop+adventure':       'hiphop+epic',
  'hiphop+action':          'hiphop+epic',
  'hiphop+cinematic':       'hiphop+epic',
  // dark group
  'hiphop+heavy':           'hiphop+dark',
  'hiphop+grim':            'hiphop+dark',
  'hiphop+deep':            'hiphop+dark',
  'hiphop+drama':           'hiphop+dark',
  // upbeat group
  'hiphop+summer':          'hiphop+upbeat',
  'hiphop+groovy':          'hiphop+upbeat',
  'hiphop+fun':             'hiphop+upbeat',
  'hiphop+dance':           'hiphop+upbeat',
  'hiphop+uplifting':       'hiphop+upbeat',
  'hiphop+inspiring':       'hiphop+upbeat',
  'hiphop+energetic':       'hiphop+upbeat',
  'hiphop+fast':            'hiphop+upbeat',
  'hiphop+positive':        'hiphop+upbeat',
  'hiphop+motivational':    'hiphop+upbeat',
  'hiphop+hopeful':         'hiphop+upbeat',
  'hiphop+funny':           'hiphop+upbeat',
  'hiphop+happy':           'hiphop+upbeat',
  'hiphop+party':           'hiphop+upbeat',
  'hiphop+advertising':     'hiphop+upbeat',
  'hiphop+commercial':      'hiphop+upbeat',
  'hiphop+children':        'hiphop+upbeat',
  'hiphop+holiday':         'hiphop+upbeat',
  'hiphop+retro':           'hiphop+upbeat',
  // epic group additions
  'hiphop+game':            'hiphop+epic',
  'hiphop+sport':           'hiphop+epic',
  'hiphop+documentary':     'hiphop+epic',
  // calm group
  'hiphop+meditative':      'hiphop+calm',
  'hiphop+nature':          'hiphop+calm',
  'hiphop+space':           'hiphop+calm',
  'hiphop+dream':           'hiphop+calm',
  'hiphop+film':            'hiphop+calm',
  'hiphop+movie':           'hiphop+calm',
  'hiphop+travel':          'hiphop+calm',
  'hiphop+soft':            'hiphop+calm',
  'hiphop+slow':            'hiphop+calm',
  'hiphop+background':      'hiphop+calm',
  'hiphop+soundscape':      'hiphop+calm',
  'hiphop+relaxing':        'hiphop+calm',
  'hiphop+cool':            'hiphop+calm',
  'hiphop+corporate':       'hiphop+calm',
  // emotional group additions
  'hiphop+sad':             'hiphop+emotional',

  // ── jazz ─────────────────────────────────────────────────────────────────
  // emotional group
  'jazz+love':              'jazz+romantic',
  'jazz+ballad':            'jazz+emotional',
  'jazz+melancholic':       'jazz+emotional',
  // epic group
  'jazz+dramatic':          'jazz+epic',
  'jazz+powerful':          'jazz+epic',
  'jazz+trailer':           'jazz+epic',
  'jazz+adventure':         'jazz+epic',
  'jazz+action':            'jazz+epic',
  'jazz+cinematic':         'jazz+epic',
  // dark group
  'jazz+heavy':             'jazz+dark',
  'jazz+grim':              'jazz+dark',
  'jazz+deep':              'jazz+dark',
  'jazz+drama':             'jazz+dark',
  // upbeat group (groove → upbeat; warm/intimate context → romantic)
  'jazz+summer':            'jazz+romantic',
  'jazz+groovy':            'jazz+upbeat',
  'jazz+fun':               'jazz+romantic',
  'jazz+dance':             'jazz+upbeat',
  'jazz+uplifting':         'jazz+romantic',
  'jazz+inspiring':         'jazz+romantic',
  'jazz+energetic':         'jazz+upbeat',
  'jazz+fast':              'jazz+upbeat',
  'jazz+positive':          'jazz+romantic',
  'jazz+motivational':      'jazz+romantic',
  'jazz+hopeful':           'jazz+romantic',
  'jazz+funny':             'jazz+romantic',
  'jazz+happy':             'jazz+romantic',
  'jazz+party':             'jazz+upbeat',
  'jazz+advertising':       'jazz+romantic',
  'jazz+commercial':        'jazz+romantic',
  'jazz+children':          'jazz+romantic',
  'jazz+holiday':           'jazz+romantic',
  'jazz+retro':             'jazz+romantic',
  // epic group additions
  'jazz+game':              'jazz+epic',
  'jazz+sport':             'jazz+epic',
  'jazz+documentary':       'jazz+epic',
  // calm group
  'jazz+meditative':        'jazz+calm',
  'jazz+nature':            'jazz+calm',
  'jazz+space':             'jazz+calm',
  'jazz+dream':             'jazz+calm',
  'jazz+film':              'jazz+calm',
  'jazz+movie':             'jazz+calm',
  'jazz+travel':            'jazz+calm',
  'jazz+soft':              'jazz+calm',
  'jazz+slow':              'jazz+calm',
  'jazz+background':        'jazz+calm',
  'jazz+soundscape':        'jazz+calm',
  'jazz+relaxing':          'jazz+calm',
  'jazz+cool':              'jazz+calm',
  'jazz+corporate':         'jazz+calm',
  // emotional group additions
  'jazz+sad':               'jazz+emotional',

  // ── rnb ──────────────────────────────────────────────────────────────────
  // emotional group
  'rnb+love':               'rnb+romantic',
  'rnb+ballad':             'rnb+emotional',
  'rnb+melancholic':        'rnb+emotional',
  // epic group
  'rnb+dramatic':           'rnb+epic',
  'rnb+powerful':           'rnb+epic',
  'rnb+trailer':            'rnb+epic',
  'rnb+adventure':          'rnb+epic',
  'rnb+action':             'rnb+epic',
  'rnb+cinematic':          'rnb+epic',
  // dark group
  'rnb+heavy':              'rnb+dark',
  'rnb+grim':               'rnb+dark',
  'rnb+deep':               'rnb+dark',
  'rnb+drama':              'rnb+dark',
  // upbeat group (groove → upbeat; warm/intimate context → romantic)
  'rnb+summer':             'rnb+romantic',
  'rnb+groovy':             'rnb+upbeat',
  'rnb+fun':                'rnb+romantic',
  'rnb+dance':              'rnb+upbeat',
  'rnb+uplifting':          'rnb+romantic',
  'rnb+inspiring':          'rnb+romantic',
  'rnb+energetic':          'rnb+upbeat',
  'rnb+fast':               'rnb+upbeat',
  'rnb+positive':           'rnb+romantic',
  'rnb+motivational':       'rnb+romantic',
  'rnb+hopeful':            'rnb+romantic',
  'rnb+funny':              'rnb+romantic',
  'rnb+happy':              'rnb+romantic',
  'rnb+party':              'rnb+upbeat',
  'rnb+advertising':        'rnb+romantic',
  'rnb+commercial':         'rnb+romantic',
  'rnb+children':           'rnb+romantic',
  'rnb+holiday':            'rnb+romantic',
  'rnb+retro':              'rnb+romantic',
  // epic group additions
  'rnb+game':               'rnb+epic',
  'rnb+sport':              'rnb+epic',
  'rnb+documentary':        'rnb+epic',
  // calm group
  'rnb+meditative':         'rnb+calm',
  'rnb+nature':             'rnb+calm',
  'rnb+space':              'rnb+calm',
  'rnb+dream':              'rnb+calm',
  'rnb+film':               'rnb+calm',
  'rnb+movie':              'rnb+calm',
  'rnb+travel':             'rnb+calm',
  'rnb+soft':               'rnb+calm',
  'rnb+slow':               'rnb+calm',
  'rnb+background':         'rnb+calm',
  'rnb+soundscape':         'rnb+calm',
  'rnb+relaxing':           'rnb+calm',
  'rnb+cool':               'rnb+calm',
  'rnb+corporate':          'rnb+calm',
  // emotional group additions
  'rnb+sad':                'rnb+emotional',

  // ── folk ─────────────────────────────────────────────────────────────────
  // emotional group
  'folk+love':              'folk+romantic',
  'folk+ballad':            'folk+emotional',
  'folk+melancholic':       'folk+emotional',
  // epic group
  'folk+dramatic':          'folk+epic',
  'folk+powerful':          'folk+epic',
  'folk+trailer':           'folk+epic',
  'folk+adventure':         'folk+epic',
  'folk+action':            'folk+epic',
  'folk+cinematic':         'folk+epic',
  // dark group
  'folk+heavy':             'folk+dark',
  'folk+grim':              'folk+dark',
  'folk+deep':              'folk+dark',
  'folk+drama':             'folk+dark',
  // upbeat group (groove/dance/party → upbeat; most else → calm)
  'folk+summer':            'folk+calm',
  'folk+groovy':            'folk+upbeat',
  'folk+fun':               'folk+calm',
  'folk+dance':             'folk+upbeat',
  'folk+uplifting':         'folk+calm',
  'folk+inspiring':         'folk+calm',
  'folk+energetic':         'folk+upbeat',
  'folk+fast':              'folk+upbeat',
  'folk+positive':          'folk+calm',
  'folk+motivational':      'folk+calm',
  'folk+hopeful':           'folk+calm',
  'folk+funny':             'folk+calm',
  'folk+happy':             'folk+calm',
  'folk+party':             'folk+upbeat',
  'folk+advertising':       'folk+calm',
  'folk+commercial':        'folk+calm',
  'folk+children':          'folk+calm',
  'folk+holiday':           'folk+calm',
  'folk+retro':             'folk+calm',
  // epic group additions
  'folk+game':              'folk+upbeat',
  'folk+sport':             'folk+upbeat',
  'folk+documentary':       'folk+epic',
  // calm group
  'folk+meditative':        'folk+calm',
  'folk+nature':            'folk+calm',
  'folk+space':             'folk+calm',
  'folk+dream':             'folk+calm',
  'folk+film':              'folk+calm',
  'folk+movie':             'folk+calm',
  'folk+travel':            'folk+calm',
  'folk+soft':              'folk+calm',
  'folk+slow':              'folk+calm',
  'folk+background':        'folk+calm',
  'folk+soundscape':        'folk+calm',
  'folk+relaxing':          'folk+calm',
  'folk+cool':              'folk+calm',
  'folk+corporate':         'folk+calm',
  // emotional group additions
  'folk+sad':               'folk+emotional',

  // ── ambient ──────────────────────────────────────────────────────────────
  // emotional group
  'ambient+love':           'ambient+romantic',
  'ambient+ballad':         'ambient+emotional',
  'ambient+melancholic':    'ambient+emotional',
  // epic group (ambient+dramatic has own ProfileConfigs entry)
  'ambient+powerful':       'ambient+epic',
  'ambient+trailer':        'ambient+epic',
  'ambient+adventure':      'ambient+epic',
  'ambient+action':         'ambient+epic',
  'ambient+cinematic':      'ambient+epic',
  // dark group
  'ambient+heavy':          'ambient+dark',
  'ambient+grim':           'ambient+dark',
  'ambient+deep':           'ambient+dark',
  'ambient+drama':          'ambient+dark',
  // upbeat group (groove/dance/party → upbeat; most else → calm)
  'ambient+summer':         'ambient+calm',
  'ambient+groovy':         'ambient+upbeat',
  'ambient+fun':            'ambient+calm',
  'ambient+dance':          'ambient+upbeat',
  'ambient+uplifting':      'ambient+calm',
  'ambient+inspiring':      'ambient+calm',
  'ambient+energetic':      'ambient+upbeat',
  'ambient+fast':           'ambient+upbeat',
  'ambient+positive':       'ambient+calm',
  'ambient+motivational':   'ambient+calm',
  'ambient+hopeful':        'ambient+calm',
  'ambient+funny':          'ambient+calm',
  'ambient+happy':          'ambient+calm',
  'ambient+party':          'ambient+upbeat',
  'ambient+advertising':    'ambient+calm',
  'ambient+commercial':     'ambient+calm',
  'ambient+children':       'ambient+calm',
  'ambient+holiday':        'ambient+calm',
  'ambient+retro':          'ambient+calm',
  // epic group additions
  'ambient+game':           'ambient+epic',
  'ambient+sport':          'ambient+epic',
  'ambient+documentary':    'ambient+epic',
  // calm group
  'ambient+meditative':     'ambient+calm',
  'ambient+nature':         'ambient+calm',
  'ambient+space':          'ambient+calm',
  'ambient+dream':          'ambient+calm',
  'ambient+film':           'ambient+calm',
  'ambient+movie':          'ambient+calm',
  'ambient+travel':         'ambient+calm',
  'ambient+soft':           'ambient+calm',
  'ambient+slow':           'ambient+calm',
  'ambient+background':     'ambient+calm',
  'ambient+soundscape':     'ambient+calm',
  'ambient+relaxing':       'ambient+calm',
  'ambient+cool':           'ambient+calm',
  'ambient+corporate':      'ambient+calm',
  // emotional group additions
  'ambient+sad':            'ambient+emotional',

  // ── classical ────────────────────────────────────────────────────────────
  // emotional group
  'classical+love':         'classical+romantic',
  'classical+ballad':       'classical+emotional',
  'classical+melancholic':  'classical+emotional',
  // epic group
  'classical+dramatic':     'classical+epic',
  'classical+powerful':     'classical+epic',
  'classical+trailer':      'classical+epic',
  'classical+adventure':    'classical+epic',
  'classical+action':       'classical+epic',
  'classical+cinematic':    'classical+epic',
  // dark group
  'classical+heavy':        'classical+dark',
  'classical+grim':         'classical+dark',
  'classical+deep':         'classical+dark',
  'classical+drama':        'classical+dark',
  // upbeat group (groove/dance/party → upbeat; most else → calm)
  'classical+summer':       'classical+calm',
  'classical+groovy':       'classical+upbeat',
  'classical+fun':          'classical+calm',
  'classical+dance':        'classical+upbeat',
  'classical+uplifting':    'classical+calm',
  'classical+inspiring':    'classical+calm',
  'classical+energetic':    'classical+upbeat',
  'classical+fast':         'classical+upbeat',
  'classical+positive':     'classical+calm',
  'classical+motivational': 'classical+calm',
  'classical+hopeful':      'classical+calm',
  'classical+funny':        'classical+calm',
  'classical+happy':        'classical+calm',
  'classical+party':        'classical+upbeat',
  'classical+advertising':  'classical+calm',
  'classical+commercial':   'classical+calm',
  'classical+children':     'classical+calm',
  'classical+holiday':      'classical+calm',
  'classical+retro':        'classical+calm',
  // epic group additions
  'classical+game':         'classical+epic',
  'classical+sport':        'classical+epic',
  'classical+documentary':  'classical+epic',
  // calm group (classical+film has own ProfileConfigs entry)
  'classical+meditative':   'classical+calm',
  'classical+nature':       'classical+calm',
  'classical+space':        'classical+calm',
  'classical+dream':        'classical+calm',
  'classical+movie':        'classical+calm',
  'classical+travel':       'classical+calm',
  'classical+soft':         'classical+calm',
  'classical+slow':         'classical+calm',
  'classical+calm':         'classical+calm',
  'classical+background':   'classical+calm',
  'classical+soundscape':   'classical+calm',
  'classical+relaxing':     'classical+calm',
  'classical+cool':         'classical+calm',
  'classical+corporate':    'classical+calm',
  // emotional group additions
  'classical+sad':          'classical+emotional',

  // ── country ──────────────────────────────────────────────────────────────
  // emotional group
  'country+love':           'country+romantic',
  'country+ballad':         'country+emotional',
  'country+melancholic':    'country+emotional',
  // epic group
  'country+dramatic':       'country+epic',
  'country+powerful':       'country+epic',
  'country+trailer':        'country+epic',
  'country+adventure':      'country+epic',
  'country+action':         'country+epic',
  'country+cinematic':      'country+epic',
  // dark group
  'country+heavy':          'country+dark',
  'country+grim':           'country+dark',
  'country+deep':           'country+dark',
  'country+drama':          'country+dark',
  // upbeat group (groove → upbeat; warm/intimate context → romantic)
  'country+summer':         'country+romantic',
  'country+groovy':         'country+upbeat',
  'country+fun':            'country+romantic',
  'country+dance':          'country+upbeat',
  'country+uplifting':      'country+romantic',
  'country+inspiring':      'country+romantic',
  'country+energetic':      'country+upbeat',
  'country+fast':           'country+upbeat',
  'country+positive':       'country+romantic',
  'country+motivational':   'country+romantic',
  'country+hopeful':        'country+romantic',
  'country+funny':          'country+romantic',
  'country+happy':          'country+upbeat',
  'country+party':          'country+upbeat',
  'country+advertising':    'country+romantic',
  'country+commercial':     'country+romantic',
  'country+children':       'country+romantic',
  'country+holiday':        'country+romantic',
  'country+retro':          'country+romantic',
  // epic group additions
  'country+game':           'country+epic',
  'country+sport':          'country+epic',
  'country+documentary':    'country+epic',
  // calm group
  'country+meditative':     'country+calm',
  'country+nature':         'country+calm',
  'country+space':          'country+calm',
  'country+dream':          'country+calm',
  'country+film':           'country+calm',
  'country+movie':          'country+calm',
  'country+travel':         'country+calm',
  'country+soft':           'country+calm',
  'country+slow':           'country+calm',
  'country+background':     'country+calm',
  'country+soundscape':     'country+calm',
  'country+relaxing':       'country+calm',
  'country+cool':           'country+calm',
  'country+corporate':      'country+calm',
  // emotional group additions
  'country+sad':            'country+emotional',

  // ── latin ────────────────────────────────────────────────────────────────
  // emotional group (latin+romantic has own ProfileConfigs entry)
  'latin+love':             'latin+romantic',
  'latin+ballad':           'latin+emotional',
  'latin+melancholic':      'latin+emotional',
  // epic group
  'latin+dramatic':         'latin+epic',
  'latin+powerful':         'latin+epic',
  'latin+trailer':          'latin+epic',
  'latin+adventure':        'latin+epic',
  'latin+action':           'latin+epic',
  'latin+cinematic':        'latin+epic',
  // dark group
  'latin+heavy':            'latin+dark',
  'latin+grim':             'latin+dark',
  'latin+deep':             'latin+dark',
  'latin+drama':            'latin+dark',
  // upbeat group (floor-filler/festive → upbeat; uplift/commercial context → romantic)
  'latin+summer':           'latin+upbeat',
  'latin+groovy':           'latin+upbeat',
  'latin+fun':              'latin+upbeat',
  'latin+dance':            'latin+upbeat',
  'latin+uplifting':        'latin+romantic',
  'latin+inspiring':        'latin+romantic',
  'latin+energetic':        'latin+upbeat',
  'latin+fast':             'latin+upbeat',
  'latin+positive':         'latin+romantic',
  'latin+motivational':     'latin+romantic',
  'latin+hopeful':          'latin+romantic',
  'latin+funny':            'latin+upbeat',
  'latin+happy':            'latin+upbeat',
  'latin+party':            'latin+upbeat',
  'latin+advertising':      'latin+romantic',
  'latin+commercial':       'latin+romantic',
  'latin+children':         'latin+romantic',
  'latin+holiday':          'latin+romantic',
  'latin+retro':            'latin+upbeat',
  // epic group additions
  'latin+game':             'latin+epic',
  'latin+sport':            'latin+epic',
  'latin+documentary':      'latin+epic',
  // calm group
  'latin+meditative':       'latin+calm',
  'latin+nature':           'latin+calm',
  'latin+space':            'latin+calm',
  'latin+dream':            'latin+calm',
  'latin+film':             'latin+calm',
  'latin+movie':            'latin+calm',
  'latin+travel':           'latin+calm',
  'latin+soft':             'latin+calm',
  'latin+slow':             'latin+calm',
  'latin+background':       'latin+calm',
  'latin+soundscape':       'latin+calm',
  'latin+relaxing':         'latin+calm',
  'latin+cool':             'latin+calm',
  'latin+corporate':        'latin+calm',
  // emotional group additions
  'latin+sad':              'latin+emotional',

  // ── reggae ───────────────────────────────────────────────────────────────
  // emotional group
  'reggae+love':            'reggae+romantic',
  'reggae+ballad':          'reggae+emotional',
  'reggae+melancholic':     'reggae+emotional',
  // epic group
  'reggae+dramatic':        'reggae+epic',
  'reggae+powerful':        'reggae+epic',
  'reggae+trailer':         'reggae+epic',
  'reggae+adventure':       'reggae+epic',
  'reggae+action':          'reggae+epic',
  'reggae+cinematic':       'reggae+epic',
  // dark group
  'reggae+heavy':           'reggae+dark',
  'reggae+grim':            'reggae+dark',
  'reggae+deep':            'reggae+dark',
  'reggae+drama':           'reggae+dark',
  // upbeat group (floor-filler/festive → upbeat; uplift/commercial context → romantic)
  'reggae+summer':          'reggae+upbeat',
  'reggae+groovy':          'reggae+upbeat',
  'reggae+fun':             'reggae+upbeat',
  'reggae+dance':           'reggae+upbeat',
  'reggae+uplifting':       'reggae+romantic',
  'reggae+inspiring':       'reggae+romantic',
  'reggae+energetic':       'reggae+upbeat',
  'reggae+fast':            'reggae+upbeat',
  'reggae+positive':        'reggae+romantic',
  'reggae+motivational':    'reggae+romantic',
  'reggae+hopeful':         'reggae+romantic',
  'reggae+funny':           'reggae+upbeat',
  'reggae+happy':           'reggae+upbeat',
  'reggae+party':           'reggae+upbeat',
  'reggae+advertising':     'reggae+romantic',
  'reggae+commercial':      'reggae+romantic',
  'reggae+children':        'reggae+romantic',
  'reggae+holiday':         'reggae+romantic',
  'reggae+retro':           'reggae+upbeat',
  // epic group additions
  'reggae+game':            'reggae+epic',
  'reggae+sport':           'reggae+epic',
  'reggae+documentary':     'reggae+epic',
  // calm group
  'reggae+meditative':      'reggae+calm',
  'reggae+nature':          'reggae+calm',
  'reggae+space':           'reggae+calm',
  'reggae+dream':           'reggae+calm',
  'reggae+film':            'reggae+calm',
  'reggae+movie':           'reggae+calm',
  'reggae+travel':          'reggae+calm',
  'reggae+soft':            'reggae+calm',
  'reggae+slow':            'reggae+calm',
  'reggae+background':      'reggae+calm',
  'reggae+soundscape':      'reggae+calm',
  'reggae+relaxing':        'reggae+calm',
  'reggae+cool':            'reggae+calm',
  'reggae+corporate':       'reggae+calm',
  // emotional group additions
  'reggae+sad':             'reggae+emotional',

  // ── funk ─────────────────────────────────────────────────────────────────
  // emotional group
  'funk+love':              'funk+romantic',
  'funk+ballad':            'funk+emotional',
  'funk+melancholic':       'funk+emotional',
  // epic group
  'funk+dramatic':          'funk+epic',
  'funk+powerful':          'funk+epic',
  'funk+trailer':           'funk+epic',
  'funk+adventure':         'funk+epic',
  'funk+action':            'funk+epic',
  'funk+cinematic':         'funk+epic',
  // dark group (funk+dark has own ProfileConfigs entry)
  'funk+heavy':             'funk+dark',
  'funk+grim':              'funk+dark',
  'funk+deep':              'funk+dark',
  'funk+drama':             'funk+dark',
  // upbeat group (floor-filler/festive → upbeat; uplift/commercial context → romantic)
  'funk+summer':            'funk+upbeat',
  'funk+fun':               'funk+upbeat',
  'funk+dance':             'funk+upbeat',
  'funk+uplifting':         'funk+romantic',
  'funk+inspiring':         'funk+romantic',
  'funk+energetic':         'funk+upbeat',
  'funk+fast':              'funk+upbeat',
  'funk+positive':          'funk+romantic',
  'funk+motivational':      'funk+romantic',
  'funk+hopeful':           'funk+romantic',
  'funk+funny':             'funk+upbeat',
  'funk+happy':             'funk+upbeat',
  'funk+party':             'funk+upbeat',
  'funk+advertising':       'funk+romantic',
  'funk+commercial':        'funk+romantic',
  'funk+children':          'funk+romantic',
  'funk+holiday':           'funk+romantic',
  'funk+retro':             'funk+upbeat',
  // epic group additions
  'funk+game':              'funk+epic',
  'funk+sport':             'funk+epic',
  'funk+documentary':       'funk+epic',
  // calm group
  'funk+meditative':        'funk+calm',
  'funk+nature':            'funk+calm',
  'funk+space':             'funk+calm',
  'funk+dream':             'funk+calm',
  'funk+film':              'funk+calm',
  'funk+movie':             'funk+calm',
  'funk+travel':            'funk+calm',
  'funk+soft':              'funk+calm',
  'funk+slow':              'funk+calm',
  'funk+background':        'funk+calm',
  'funk+soundscape':        'funk+calm',
  'funk+relaxing':          'funk+calm',
  'funk+cool':              'funk+calm',
  'funk+corporate':         'funk+calm',
  // emotional group additions
  'funk+sad':               'funk+emotional',

  // ── blues ────────────────────────────────────────────────────────────────
  // emotional group (blues IS sad — both sad and emotional collapse to blues+emotional)
  'blues+sad':              'blues+emotional',
  'blues+love':             'blues+romantic',
  'blues+ballad':           'blues+emotional',
  'blues+melancholic':      'blues+emotional',
  // epic group
  'blues+dramatic':         'blues+epic',
  'blues+powerful':         'blues+epic',
  'blues+trailer':          'blues+epic',
  'blues+adventure':        'blues+epic',
  'blues+action':           'blues+epic',
  'blues+cinematic':        'blues+epic',
  // dark group
  'blues+heavy':            'blues+dark',
  'blues+grim':             'blues+dark',
  'blues+deep':             'blues+dark',
  'blues+drama':            'blues+dark',
  // upbeat group (blues energy = shuffle/groove → romantic; only true floor-fillers stay upbeat)
  'blues+summer':           'blues+romantic',
  'blues+groovy':           'blues+romantic',
  'blues+fun':              'blues+romantic',
  'blues+dance':            'blues+upbeat',
  'blues+uplifting':        'blues+romantic',
  'blues+inspiring':        'blues+romantic',
  'blues+energetic':        'blues+upbeat',
  'blues+fast':             'blues+upbeat',
  'blues+positive':         'blues+romantic',
  'blues+motivational':     'blues+romantic',
  'blues+hopeful':          'blues+romantic',
  'blues+funny':            'blues+romantic',
  'blues+happy':            'blues+romantic',
  'blues+party':            'blues+upbeat',
  'blues+advertising':      'blues+romantic',
  'blues+commercial':       'blues+romantic',
  'blues+children':         'blues+romantic',
  'blues+holiday':          'blues+romantic',
  'blues+retro':            'blues+upbeat',
  // epic group additions
  'blues+game':             'blues+epic',
  'blues+sport':            'blues+epic',
  'blues+documentary':      'blues+epic',
  // calm group
  'blues+meditative':       'blues+calm',
  'blues+nature':           'blues+calm',
  'blues+space':            'blues+calm',
  'blues+dream':            'blues+calm',
  'blues+film':             'blues+calm',
  'blues+movie':            'blues+calm',
  'blues+travel':           'blues+calm',
  'blues+soft':             'blues+calm',
  'blues+slow':             'blues+calm',
  'blues+background':       'blues+calm',
  'blues+soundscape':       'blues+calm',
  'blues+relaxing':         'blues+calm',
  'blues+cool':             'blues+calm',
  'blues+corporate':        'blues+calm',

  // ── metal ────────────────────────────────────────────────────────────────
  // emotional group → hardrock+emotional (metal doesn't do soft)
  'metal+emotional':        'hardrock+emotional',
  'metal+love':             'hardrock+emotional',
  'metal+romantic':         'hardrock+emotional',
  'metal+ballad':           'hardrock+emotional',
  'metal+melancholic':      'hardrock+emotional',
  // epic group
  'metal+dramatic':         'metal+epic',
  'metal+powerful':         'metal+epic',
  'metal+trailer':          'metal+epic',
  'metal+adventure':        'metal+epic',
  'metal+action':           'metal+epic',
  'metal+cinematic':        'metal+epic',
  // dark group (metal+dark has own ProfileConfigs entry)
  'metal+heavy':            'metal+dark',
  'metal+grim':             'metal+dark',
  'metal+deep':             'metal+dark',
  'metal+drama':            'metal+dark',
  // upbeat group
  'metal+summer':           'metal+upbeat',
  'metal+groovy':           'metal+upbeat',
  'metal+fun':              'metal+upbeat',
  'metal+dance':            'metal+upbeat',
  'metal+uplifting':        'metal+epic',
  'metal+inspiring':        'metal+epic',
  'metal+energetic':        'metal+epic',
  'metal+fast':             'metal+upbeat',
  'metal+positive':         'metal+upbeat',
  'metal+motivational':     'metal+upbeat',
  'metal+hopeful':          'metal+upbeat',
  'metal+funny':            'metal+upbeat',
  'metal+happy':            'metal+epic',
  'metal+party':            'metal+upbeat',
  'metal+advertising':      'metal+upbeat',
  'metal+commercial':       'metal+upbeat',
  'metal+children':         'metal+upbeat',
  'metal+holiday':          'metal+upbeat',
  'metal+retro':            'metal+upbeat',
  // epic group additions
  'metal+game':             'metal+epic',
  'metal+sport':            'metal+epic',
  'metal+documentary':      'metal+epic',
  // calm group (metal+space has own ProfileConfigs entry)
  'metal+meditative':       'metal+calm',
  'metal+nature':           'metal+calm',
  'metal+dream':            'metal+calm',
  'metal+film':             'metal+calm',
  'metal+movie':            'metal+calm',
  'metal+travel':           'metal+calm',
  'metal+soft':             'metal+calm',
  'metal+slow':             'metal+calm',
  'metal+background':       'metal+calm',
  'metal+soundscape':       'metal+calm',
  'metal+relaxing':         'metal+calm',
  'metal+cool':             'metal+calm',
  'metal+corporate':        'metal+calm',
  // emotional group additions
  'metal+sad':              'metal+emotional',

  // ── hardrock ─────────────────────────────────────────────────────────────
  // emotional group
  'hardrock+love':          'hardrock+romantic',
  'hardrock+ballad':        'hardrock+emotional',
  'hardrock+melancholic':   'hardrock+emotional',
  // epic group
  'hardrock+dramatic':      'hardrock+epic',
  'hardrock+powerful':      'hardrock+epic',
  'hardrock+trailer':       'hardrock+epic',
  'hardrock+adventure':     'hardrock+epic',
  'hardrock+action':        'hardrock+epic',
  'hardrock+cinematic':     'hardrock+epic',
  // dark group
  'hardrock+heavy':         'hardrock+dark',
  'hardrock+grim':          'hardrock+dark',
  'hardrock+deep':          'hardrock+dark',
  'hardrock+drama':         'hardrock+dark',
  // upbeat group
  'hardrock+summer':        'hardrock+upbeat',
  'hardrock+groovy':        'hardrock+upbeat',
  'hardrock+fun':           'hardrock+upbeat',
  'hardrock+dance':         'hardrock+upbeat',
  'hardrock+uplifting':     'hardrock+epic',
  'hardrock+inspiring':     'hardrock+epic',
  'hardrock+energetic':     'hardrock+epic',
  'hardrock+fast':          'hardrock+upbeat',
  'hardrock+positive':      'hardrock+upbeat',
  'hardrock+motivational':  'hardrock+upbeat',
  'hardrock+hopeful':       'hardrock+upbeat',
  'hardrock+funny':         'hardrock+upbeat',
  'hardrock+happy':         'hardrock+epic',
  'hardrock+party':         'hardrock+upbeat',
  'hardrock+advertising':   'hardrock+upbeat',
  'hardrock+commercial':    'hardrock+upbeat',
  'hardrock+children':      'hardrock+upbeat',
  'hardrock+holiday':       'hardrock+upbeat',
  'hardrock+retro':         'hardrock+upbeat',
  // epic group additions
  'hardrock+game':          'hardrock+epic',
  'hardrock+sport':         'hardrock+epic',
  'hardrock+documentary':   'hardrock+epic',
  // calm group
  'hardrock+meditative':    'hardrock+calm',
  'hardrock+nature':        'hardrock+calm',
  'hardrock+space':         'hardrock+calm',
  'hardrock+dream':         'hardrock+calm',
  'hardrock+film':          'hardrock+calm',
  'hardrock+movie':         'hardrock+calm',
  'hardrock+travel':        'hardrock+calm',
  'hardrock+soft':          'hardrock+calm',
  'hardrock+slow':          'hardrock+calm',
  'hardrock+background':    'hardrock+calm',
  'hardrock+soundscape':    'hardrock+calm',
  'hardrock+relaxing':      'hardrock+calm',
  'hardrock+cool':          'hardrock+calm',
  'hardrock+corporate':     'hardrock+calm',
  // emotional group additions
  'hardrock+sad':           'hardrock+emotional',

  // ── dance ────────────────────────────────────────────────────────────────
  // emotional group
  'dance+love':             'dance+romantic',
  'dance+ballad':           'dance+emotional',
  'dance+melancholic':      'dance+emotional',
  // epic group
  'dance+dramatic':         'dance+epic',
  'dance+powerful':         'dance+epic',
  'dance+trailer':          'dance+epic',
  'dance+adventure':        'dance+epic',
  'dance+action':           'dance+epic',
  'dance+cinematic':        'dance+epic',
  // dark group
  'dance+heavy':            'dance+dark',
  'dance+grim':             'dance+dark',
  'dance+deep':             'dance+dark',
  'dance+drama':            'dance+dark',
  // upbeat group
  'dance+summer':           'dance+upbeat',
  'dance+groovy':           'dance+upbeat',
  'dance+fun':              'dance+upbeat',
  'dance+uplifting':        'dance+upbeat',
  'dance+inspiring':        'dance+upbeat',
  'dance+energetic':        'dance+upbeat',
  'dance+fast':             'dance+upbeat',
  'dance+positive':         'dance+upbeat',
  'dance+motivational':     'dance+upbeat',
  'dance+hopeful':          'dance+upbeat',
  'dance+funny':            'dance+upbeat',
  'dance+happy':            'dance+upbeat',
  'dance+party':            'dance+upbeat',
  'dance+advertising':      'dance+upbeat',
  'dance+commercial':       'dance+upbeat',
  'dance+children':         'dance+upbeat',
  'dance+holiday':          'dance+upbeat',
  'dance+retro':            'dance+upbeat',
  // epic group additions
  'dance+game':             'dance+epic',
  'dance+sport':            'dance+epic',
  'dance+documentary':      'dance+epic',
  // calm group
  'dance+meditative':       'dance+calm',
  'dance+nature':           'dance+calm',
  'dance+space':            'dance+calm',
  'dance+dream':            'dance+calm',
  'dance+film':             'dance+calm',
  'dance+movie':            'dance+calm',
  'dance+travel':           'dance+calm',
  'dance+soft':             'dance+calm',
  'dance+slow':             'dance+calm',
  'dance+background':       'dance+calm',
  'dance+soundscape':       'dance+calm',
  'dance+relaxing':         'dance+calm',
  'dance+cool':             'dance+calm',
  'dance+corporate':        'dance+calm',
  // emotional group additions
  'dance+sad':              'dance+emotional',

  // ── house ────────────────────────────────────────────────────────────────
  // emotional group
  'house+love':             'house+romantic',
  'house+ballad':           'house+emotional',
  'house+melancholic':      'house+emotional',
  // epic group
  'house+dramatic':         'house+epic',
  'house+powerful':         'house+epic',
  'house+trailer':          'house+epic',
  'house+adventure':        'house+epic',
  'house+action':           'house+epic',
  'house+cinematic':        'house+epic',
  // dark group
  'house+heavy':            'house+dark',
  'house+grim':             'house+dark',
  'house+deep':             'house+dark',
  'house+drama':            'house+dark',
  // upbeat group
  'house+summer':           'house+upbeat',
  'house+groovy':           'house+upbeat',
  'house+fun':              'house+upbeat',
  'house+dance':            'house+upbeat',
  'house+uplifting':        'house+upbeat',
  'house+inspiring':        'house+upbeat',
  'house+energetic':        'house+upbeat',
  'house+fast':             'house+upbeat',
  'house+positive':         'house+upbeat',
  'house+motivational':     'house+upbeat',
  'house+hopeful':          'house+upbeat',
  'house+funny':            'house+upbeat',
  'house+happy':            'house+upbeat',
  'house+party':            'house+upbeat',
  'house+advertising':      'house+upbeat',
  'house+commercial':       'house+upbeat',
  'house+children':         'house+upbeat',
  'house+holiday':          'house+upbeat',
  'house+retro':            'house+upbeat',
  // epic group additions
  'house+game':             'house+epic',
  'house+sport':            'house+epic',
  'house+documentary':      'house+epic',
  // calm group
  'house+meditative':       'house+calm',
  'house+nature':           'house+calm',
  'house+space':            'house+calm',
  'house+dream':            'house+calm',
  'house+film':             'house+calm',
  'house+movie':            'house+calm',
  'house+travel':           'house+calm',
  'house+soft':             'house+calm',
  'house+slow':             'house+calm',
  'house+background':       'house+calm',
  'house+soundscape':       'house+calm',
  'house+relaxing':         'house+calm',
  'house+cool':             'house+calm',
  'house+corporate':        'house+calm',
  // emotional group additions
  'house+sad':              'house+emotional',

  // ── disco ────────────────────────────────────────────────────────────────
  // emotional group
  'disco+love':             'disco+romantic',
  'disco+ballad':           'disco+emotional',
  'disco+melancholic':      'disco+emotional',
  // epic group
  'disco+dramatic':         'disco+epic',
  'disco+powerful':         'disco+epic',
  'disco+trailer':          'disco+epic',
  'disco+adventure':        'disco+epic',
  'disco+action':           'disco+epic',
  'disco+cinematic':        'disco+epic',
  // dark group
  'disco+heavy':            'disco+dark',
  'disco+grim':             'disco+dark',
  'disco+deep':             'disco+dark',
  'disco+drama':            'disco+dark',
  // upbeat group
  'disco+summer':           'disco+upbeat',
  'disco+groovy':           'disco+upbeat',
  'disco+fun':              'disco+upbeat',
  'disco+dance':            'disco+upbeat',
  'disco+uplifting':        'disco+upbeat',
  'disco+inspiring':        'disco+upbeat',
  'disco+energetic':        'disco+upbeat',
  'disco+fast':             'disco+upbeat',
  'disco+positive':         'disco+upbeat',
  'disco+motivational':     'disco+upbeat',
  'disco+hopeful':          'disco+upbeat',
  'disco+funny':            'disco+upbeat',
  'disco+happy':            'disco+upbeat',
  'disco+party':            'disco+upbeat',
  'disco+advertising':      'disco+upbeat',
  'disco+commercial':       'disco+upbeat',
  'disco+children':         'disco+upbeat',
  'disco+holiday':          'disco+upbeat',
  'disco+retro':            'disco+upbeat',
  // epic group additions
  'disco+game':             'disco+epic',
  'disco+sport':            'disco+epic',
  'disco+documentary':      'disco+epic',
  // calm group
  'disco+meditative':       'disco+calm',
  'disco+nature':           'disco+calm',
  'disco+space':            'disco+calm',
  'disco+dream':            'disco+calm',
  'disco+film':             'disco+calm',
  'disco+movie':            'disco+calm',
  'disco+travel':           'disco+calm',
  'disco+soft':             'disco+calm',
  'disco+slow':             'disco+calm',
  'disco+background':       'disco+calm',
  'disco+soundscape':       'disco+calm',
  'disco+relaxing':         'disco+calm',
  'disco+cool':             'disco+calm',
  'disco+corporate':        'disco+calm',
  // emotional group additions
  'disco+sad':              'disco+emotional',

  // ── chillout ─────────────────────────────────────────────────────────────
  // emotional group
  'chillout+love':          'chillout+romantic',
  'chillout+ballad':        'chillout+emotional',
  'chillout+melancholic':   'chillout+emotional',
  // epic group
  'chillout+dramatic':      'chillout+epic',
  'chillout+powerful':      'chillout+epic',
  'chillout+trailer':       'chillout+epic',
  'chillout+adventure':     'chillout+epic',
  'chillout+action':        'chillout+epic',
  'chillout+cinematic':     'chillout+epic',
  // dark group
  'chillout+heavy':         'chillout+dark',
  'chillout+grim':          'chillout+dark',
  'chillout+deep':          'chillout+dark',
  'chillout+drama':         'chillout+dark',
  // upbeat group (groove/dance/party → upbeat; most else → calm)
  'chillout+summer':        'chillout+calm',
  'chillout+groovy':        'chillout+upbeat',
  'chillout+fun':           'chillout+calm',
  'chillout+dance':         'chillout+upbeat',
  'chillout+uplifting':     'chillout+calm',
  'chillout+inspiring':     'chillout+calm',
  'chillout+energetic':     'chillout+upbeat',
  'chillout+fast':          'chillout+upbeat',
  'chillout+positive':      'chillout+calm',
  'chillout+motivational':  'chillout+calm',
  'chillout+hopeful':       'chillout+calm',
  'chillout+funny':         'chillout+calm',
  'chillout+happy':         'chillout+calm',
  'chillout+party':         'chillout+upbeat',
  'chillout+advertising':   'chillout+calm',
  'chillout+commercial':    'chillout+calm',
  'chillout+children':      'chillout+calm',
  'chillout+holiday':       'chillout+calm',
  'chillout+retro':         'chillout+calm',
  // epic group additions
  'chillout+game':          'chillout+epic',
  'chillout+sport':         'chillout+epic',
  'chillout+documentary':   'chillout+epic',
  // calm group
  'chillout+meditative':    'chillout+calm',
  'chillout+nature':        'chillout+calm',
  'chillout+space':         'chillout+calm',
  'chillout+dream':         'chillout+calm',
  'chillout+film':          'chillout+calm',
  'chillout+movie':         'chillout+calm',
  'chillout+travel':        'chillout+calm',
  'chillout+soft':          'chillout+calm',
  'chillout+slow':          'chillout+calm',
  'chillout+background':    'chillout+calm',
  'chillout+soundscape':    'chillout+calm',
  'chillout+relaxing':      'chillout+calm',
  'chillout+cool':          'chillout+calm',
  'chillout+corporate':     'chillout+calm',
  // emotional group additions
  'chillout+sad':           'chillout+emotional',

  // ── triphop ──────────────────────────────────────────────────────────────
  // emotional group (triphop is melancholic by nature; keep emotional distinct)
  'triphop+love':           'triphop+romantic',
  'triphop+ballad':         'triphop+emotional',
  'triphop+melancholic':    'triphop+emotional',
  // epic group
  'triphop+dramatic':       'triphop+epic',
  'triphop+powerful':       'triphop+epic',
  'triphop+trailer':        'triphop+epic',
  'triphop+adventure':      'triphop+epic',
  'triphop+action':         'triphop+epic',
  'triphop+cinematic':      'triphop+epic',
  // dark group
  'triphop+heavy':          'triphop+dark',
  'triphop+grim':           'triphop+dark',
  'triphop+deep':           'triphop+dark',
  'triphop+drama':          'triphop+dark',
  // upbeat group (trip-hop energy = cinematic groove, not dance floor)
  'triphop+summer':         'triphop+romantic',
  'triphop+groovy':         'triphop+upbeat',
  'triphop+fun':            'triphop+upbeat',
  'triphop+dance':          'triphop+upbeat',
  'triphop+uplifting':      'triphop+romantic',
  'triphop+inspiring':      'triphop+romantic',
  'triphop+energetic':      'triphop+epic',
  'triphop+fast':           'triphop+upbeat',
  'triphop+positive':       'triphop+romantic',
  'triphop+motivational':   'triphop+epic',
  'triphop+hopeful':        'triphop+romantic',
  'triphop+funny':          'triphop+calm',
  'triphop+happy':          'triphop+romantic',
  'triphop+party':          'triphop+upbeat',
  'triphop+advertising':    'triphop+calm',
  'triphop+commercial':     'triphop+calm',
  'triphop+children':       'triphop+calm',
  'triphop+holiday':        'triphop+calm',
  'triphop+retro':          'triphop+calm',
  // epic group additions
  'triphop+game':           'triphop+epic',
  'triphop+sport':          'triphop+epic',
  'triphop+documentary':    'triphop+epic',
  // calm group
  'triphop+meditative':     'triphop+calm',
  'triphop+nature':         'triphop+calm',
  'triphop+space':          'triphop+calm',
  'triphop+dream':          'triphop+calm',
  'triphop+film':           'triphop+calm',
  'triphop+movie':          'triphop+calm',
  'triphop+travel':         'triphop+calm',
  'triphop+soft':           'triphop+calm',
  'triphop+slow':           'triphop+calm',
  'triphop+background':     'triphop+calm',
  'triphop+soundscape':     'triphop+calm',
  'triphop+relaxing':       'triphop+calm',
  'triphop+cool':           'triphop+calm',
  'triphop+corporate':      'triphop+calm',
  // emotional group additions
  'triphop+sad':            'triphop+emotional',

  // ── newage ───────────────────────────────────────────────────────────────
  // emotional group
  'newage+love':            'newage+romantic',
  'newage+ballad':          'newage+emotional',
  'newage+melancholic':     'newage+emotional',
  // epic group
  'newage+dramatic':        'newage+epic',
  'newage+powerful':        'newage+epic',
  'newage+trailer':         'newage+epic',
  'newage+adventure':       'newage+epic',
  'newage+action':          'newage+epic',
  'newage+cinematic':       'newage+epic',
  // dark group
  'newage+heavy':           'newage+dark',
  'newage+grim':            'newage+dark',
  'newage+deep':            'newage+dark',
  'newage+drama':           'newage+dark',
  // upbeat group (new age energy = ethereal/uplifting, not dance floor)
  'newage+summer':          'newage+calm',
  'newage+groovy':          'newage+upbeat',
  'newage+fun':             'newage+calm',
  'newage+dance':           'newage+upbeat',
  'newage+uplifting':       'newage+upbeat',
  'newage+inspiring':       'newage+upbeat',
  'newage+energetic':       'newage+epic',
  'newage+fast':            'newage+upbeat',
  'newage+positive':        'newage+calm',
  'newage+motivational':    'newage+upbeat',
  'newage+hopeful':         'newage+calm',
  'newage+funny':           'newage+calm',
  'newage+happy':           'newage+calm',
  'newage+party':           'newage+upbeat',
  'newage+advertising':     'newage+calm',
  'newage+commercial':      'newage+calm',
  'newage+children':        'newage+calm',
  'newage+holiday':         'newage+calm',
  'newage+retro':           'newage+calm',
  // epic group additions
  'newage+game':            'newage+epic',
  'newage+sport':           'newage+epic',
  'newage+documentary':     'newage+epic',
  // calm group
  'newage+meditative':      'newage+calm',
  'newage+nature':          'newage+calm',
  'newage+space':           'newage+calm',
  'newage+dream':           'newage+calm',
  'newage+film':            'newage+calm',
  'newage+movie':           'newage+calm',
  'newage+travel':          'newage+calm',
  'newage+soft':            'newage+calm',
  'newage+slow':            'newage+calm',
  'newage+background':      'newage+calm',
  'newage+soundscape':      'newage+calm',
  'newage+relaxing':        'newage+calm',
  'newage+cool':            'newage+calm',
  'newage+corporate':       'newage+calm',
  // emotional group additions
  'newage+sad':             'newage+emotional',

  // ── psychedelic ──────────────────────────────────────────────────────────
  // emotional group
  'psychedelic+love':       'psychedelic+romantic',
  'psychedelic+ballad':     'psychedelic+emotional',
  'psychedelic+melancholic':'psychedelic+emotional',
  // epic group
  'psychedelic+dramatic':   'psychedelic+epic',
  'psychedelic+powerful':   'psychedelic+epic',
  'psychedelic+trailer':    'psychedelic+epic',
  'psychedelic+adventure':  'psychedelic+epic',
  'psychedelic+action':     'psychedelic+epic',
  'psychedelic+cinematic':  'psychedelic+epic',
  // dark group (psychedelic+dark has own ProfileConfigs entry)
  'psychedelic+heavy':      'psychedelic+dark',
  'psychedelic+grim':       'psychedelic+dark',
  'psychedelic+deep':       'psychedelic+dark',
  'psychedelic+drama':      'psychedelic+dark',
  // upbeat group (groove/dance/party → upbeat; most else → calm)
  'psychedelic+summer':     'psychedelic+calm',
  'psychedelic+groovy':     'psychedelic+upbeat',
  'psychedelic+fun':        'psychedelic+calm',
  'psychedelic+dance':      'psychedelic+upbeat',
  'psychedelic+uplifting':  'psychedelic+calm',
  'psychedelic+inspiring':  'psychedelic+calm',
  'psychedelic+energetic':  'psychedelic+epic',
  'psychedelic+fast':       'psychedelic+upbeat',
  'psychedelic+positive':   'psychedelic+calm',
  'psychedelic+motivational':'psychedelic+calm',
  'psychedelic+hopeful':    'psychedelic+calm',
  'psychedelic+funny':      'psychedelic+calm',
  'psychedelic+happy':      'psychedelic+calm',
  'psychedelic+party':      'psychedelic+upbeat',
  'psychedelic+advertising':'psychedelic+calm',
  'psychedelic+commercial': 'psychedelic+calm',
  'psychedelic+children':   'psychedelic+calm',
  'psychedelic+holiday':    'psychedelic+calm',
  'psychedelic+retro':      'psychedelic+calm',
  // calm group
  'psychedelic+meditative': 'psychedelic+calm',
  'psychedelic+nature':     'psychedelic+calm',
  'psychedelic+space':      'psychedelic+calm',
  'psychedelic+dream':      'psychedelic+calm',
  'psychedelic+film':       'psychedelic+calm',
  'psychedelic+movie':      'psychedelic+calm',
  'psychedelic+travel':     'psychedelic+calm',
  'psychedelic+soft':       'psychedelic+calm',
  'psychedelic+slow':       'psychedelic+calm',
  'psychedelic+background': 'psychedelic+calm',
  'psychedelic+soundscape': 'psychedelic+calm',
  'psychedelic+relaxing':   'psychedelic+calm',
  'psychedelic+cool':       'psychedelic+calm',
  'psychedelic+corporate':  'psychedelic+calm',
  // emotional group additions
  'psychedelic+sad':        'psychedelic+emotional',

  // ── energetic ────────────────────────────────────────────────────────────
  // emotional group
  'energetic+love':         'energetic+romantic',
  'energetic+ballad':       'energetic+emotional',
  'energetic+melancholic':  'energetic+emotional',
  // epic group
  'energetic+dramatic':     'energetic+epic',
  'energetic+powerful':     'energetic+epic',
  'energetic+trailer':      'energetic+epic',
  'energetic+adventure':    'energetic+epic',
  'energetic+action':       'energetic+epic',
  'energetic+cinematic':    'energetic+epic',
  // dark group
  'energetic+heavy':        'energetic+dark',
  'energetic+grim':         'energetic+dark',
  'energetic+deep':         'energetic+dark',
  'energetic+drama':        'energetic+dark',
  // upbeat group
  'energetic+summer':       'energetic+upbeat',
  'energetic+groovy':       'energetic+upbeat',
  'energetic+fun':          'energetic+upbeat',
  'energetic+dance':        'energetic+upbeat',
  'energetic+uplifting':    'energetic+upbeat',
  'energetic+inspiring':    'energetic+upbeat',
  'energetic+energetic':    'energetic+upbeat',
  'energetic+fast':         'energetic+upbeat',
  'energetic+positive':     'energetic+upbeat',
  'energetic+motivational': 'energetic+upbeat',
  'energetic+hopeful':      'energetic+upbeat',
  'energetic+funny':        'energetic+upbeat',
  'energetic+happy':        'energetic+upbeat',
  'energetic+party':        'energetic+upbeat',
  'energetic+advertising':  'energetic+upbeat',
  'energetic+commercial':   'energetic+upbeat',
  'energetic+children':     'energetic+upbeat',
  'energetic+holiday':      'energetic+upbeat',
  'energetic+retro':        'energetic+upbeat',
  // epic group additions
  'energetic+game':         'energetic+epic',
  'energetic+sport':        'energetic+epic',
  'energetic+documentary':  'energetic+epic',
  // calm group
  'energetic+meditative':   'energetic+calm',
  'energetic+nature':       'energetic+calm',
  'energetic+space':        'energetic+calm',
  'energetic+dream':        'energetic+calm',
  'energetic+film':         'energetic+calm',
  'energetic+movie':        'energetic+calm',
  'energetic+travel':       'energetic+calm',
  'energetic+soft':         'energetic+calm',
  'energetic+slow':         'energetic+calm',
  'energetic+background':   'energetic+calm',
  'energetic+soundscape':   'energetic+calm',
  'energetic+relaxing':     'energetic+calm',
  'energetic+cool':         'energetic+calm',
  'energetic+corporate':    'energetic+calm',
  // emotional group additions
  'energetic+sad':          'energetic+emotional',

  // ── easylistening ────────────────────────────────────────────────────────
  // emotional group
  'easylistening+love':         'easylistening+romantic',
  'easylistening+ballad':       'easylistening+emotional',
  'easylistening+melancholic':  'easylistening+emotional',
  // epic group
  'easylistening+dramatic':     'easylistening+epic',
  'easylistening+powerful':     'easylistening+epic',
  'easylistening+trailer':      'easylistening+epic',
  'easylistening+adventure':    'easylistening+epic',
  'easylistening+action':       'easylistening+epic',
  'easylistening+cinematic':    'easylistening+epic',
  // dark group
  'easylistening+heavy':        'easylistening+dark',
  'easylistening+grim':         'easylistening+dark',
  'easylistening+deep':         'easylistening+dark',
  // upbeat group
  'easylistening+summer':       'easylistening+upbeat',
  'easylistening+groovy':       'easylistening+upbeat',
  'easylistening+fun':          'easylistening+upbeat',
  'easylistening+dance':        'easylistening+upbeat',
  'easylistening+uplifting':    'easylistening+upbeat',
  'easylistening+inspiring':    'easylistening+upbeat',
  // calm group
  'easylistening+meditative':   'easylistening+calm',
  'easylistening+nature':       'easylistening+calm',
  'easylistening+space':        'easylistening+calm',
  'easylistening+dream':        'easylistening+calm',
  'easylistening+film':         'easylistening+calm',
  'easylistening+movie':        'easylistening+calm',
  'easylistening+travel':       'easylistening+calm',
  'easylistening+soft':         'easylistening+calm',
  'easylistening+slow':         'easylistening+calm',

  // ── wildcards → existing named profiles (cross-genre, intentional) ───────
  '*+sexy':                 'sexy',
  '*+sad':                  'sad',
  '*+happy':                'happy',
  '*+party':                'house',
};

// Blends top-2 genres into a single resolved genre.
// Key: `${genre1}+${genre2}` — always put the higher-scored genre first.
// Value: a valid ProfileConfigs base key (bare genre).
// Combos not listed fall back to genre1 (dominant genre).
export const GenreBlendMap: Record<string, string> = {
  // rock blends
  'rock+pop':               'rock',
  'rock+electronic':        'hardrock',
  'rock+hiphop':            'rock',
  'rock+rnb':               'rock',
  'rock+folk':              'folk',
  'rock+blues':             'blues',
  'rock+metal':             'metal',
  'rock+hardrock':          'hardrock',
  'rock+punk':              'hardrock',
  'rock+country':           'country',
  'rock+jazz':              'blues',
  'rock+funk':              'funk',
  'rock+latin':             'rock',
  'rock+psychedelic':       'psychedelic',
  'rock+ambient':           'ambient',
  'rock+classical':         'rock',
  'rock+dance':             'rock',
  'rock+reggae':            'reggae',
  // pop blends
  'pop+rock':               'rock',
  'pop+electronic':         'pop',
  'pop+hiphop':             'hiphop',
  'pop+rnb':                'rnb',
  'pop+folk':               'folk',
  'pop+dance':              'pop',
  'pop+jazz':               'jazz',
  'pop+country':            'country',
  'pop+funk':               'funk',
  'pop+latin':              'latin',
  'pop+classical':          'pop',
  'pop+reggae':             'reggae',
  'pop+blues':              'rnb',
  // electronic blends
  'electronic+dance':       'dance',
  'electronic+house':       'house',
  'electronic+hiphop':      'hiphop',
  'electronic+pop':         'pop',
  'electronic+ambient':     'ambient',
  'electronic+rock':        'hardrock',
  'electronic+jazz':        'triphop',
  'electronic+rnb':         'triphop',
  'electronic+metal':       'metal',
  'electronic+funk':        'funk',
  'electronic+classical':   'ambient',
  'electronic+folk':        'ambient',
  'electronic+psychedelic': 'psychedelic',
  // darkambient blends
  'darkambient+electronic': 'ambient',
  'darkambient+ambient':    'ambient',
  // triphop blends
  'triphop+electronic':     'electronic',
  'triphop+hiphop':         'hiphop',
  'triphop+ambient':        'ambient',
  'triphop+jazz':           'jazz',
  'triphop+rnb':            'rnb',
  // hiphop blends
  'hiphop+rnb':             'rnb',
  'hiphop+pop':             'hiphop',
  'hiphop+electronic':      'hiphop',
  'hiphop+funk':            'funk',
  'hiphop+jazz':            'triphop',
  'hiphop+blues':           'blues',
  'hiphop+rock':            'hiphop',
  'hiphop+latin':           'latin',
  'hiphop+reggae':          'reggae',
  'hiphop+dance':           'dance',
  // rnb blends
  'rnb+hiphop':             'rnb',
  'rnb+pop':                'rnb',
  'rnb+jazz':               'jazz',
  'rnb+soul':               'rnb',
  'rnb+funk':               'funk',
  'rnb+blues':              'blues',
  'rnb+electronic':         'triphop',
  'rnb+dance':              'rnb',
  'rnb+latin':              'latin',
  'rnb+country':            'country',
  // jazz blends
  'jazz+blues':             'blues',
  'jazz+funk':              'funk',
  'jazz+rnb':               'rnb',
  'jazz+latin':             'latin',
  'jazz+electronic':        'triphop',
  'jazz+hiphop':            'triphop',
  'jazz+classical':         'classical',
  'jazz+folk':              'folk',
  'jazz+pop':               'jazz',
  'jazz+rock':              'blues',
  // blues blends
  'blues+rock':             'blues',
  'blues+jazz':             'blues',
  'blues+folk':             'folk',
  'blues+country':          'country',
  'blues+rnb':              'blues',
  'blues+funk':             'funk',
  'blues+electronic':       'blues',
  // folk blends
  'folk+country':           'country',
  'folk+rock':              'rock',
  'folk+pop':               'folk',
  'folk+blues':             'folk',
  'folk+classical':         'classical',
  'folk+ambient':           'ambient',
  'folk+jazz':              'folk',
  'folk+latin':             'latin',
  // classical blends
  'classical+ambient':      'ambient',
  'classical+folk':         'classical',
  'classical+jazz':         'jazz',
  'classical+electronic':   'ambient',
  'classical+pop':          'classical',
  'classical+rock':         'classical',
  // country blends
  'country+folk':           'folk',
  'country+rock':           'rock',
  'country+pop':            'country',
  'country+blues':          'blues',
  'country+jazz':           'jazz',
  // latin blends
  'latin+pop':              'latin',
  'latin+rock':             'latin',
  'latin+jazz':             'jazz',
  'latin+reggae':           'reggae',
  'latin+funk':             'funk',
  'latin+electronic':       'latin',
  'latin+hiphop':           'hiphop',
  // dance blends
  'dance+electronic':       'electronic',
  'dance+house':            'house',
  'dance+pop':              'dance',
  'dance+hiphop':           'hiphop',
  'dance+latin':            'latin',
  'dance+funk':             'funk',
  'dance+disco':            'disco',
  // house blends
  'house+electronic':       'electronic',
  'house+dance':            'house',
  'house+techno':           'electronic',
  'house+ambient':          'ambient',
  'house+pop':              'house',
  // disco blends
  'disco+funk':             'funk',
  'disco+pop':              'disco',
  'disco+dance':            'dance',
  'disco+rnb':              'rnb',
  // metal blends
  'metal+hardrock':         'metal',
  'metal+rock':             'metal',
  'metal+electronic':       'metal',
  'metal+blues':            'blues',
  // hardrock blends
  'hardrock+metal':         'metal',
  'hardrock+rock':          'hardrock',
  'hardrock+electronic':    'hardrock',
  'hardrock+blues':         'blues',
  'hardrock+punk':          'hardrock',
  // funk blends
  'funk+rnb':               'rnb',
  'funk+jazz':              'jazz',
  'funk+soul':              'rnb',
  'funk+pop':               'funk',
  'funk+hiphop':            'hiphop',
  'funk+disco':             'disco',
  'funk+latin':             'latin',
  // reggae blends
  'reggae+hiphop':          'hiphop',
  'reggae+folk':            'folk',
  'reggae+pop':             'reggae',
  'reggae+latin':           'latin',
  'reggae+electronic':      'electronic',
  // ambient blends
  'ambient+electronic':     'ambient',
  'ambient+classical':      'classical',
  'ambient+folk':           'folk',
  'ambient+newage':         'newage',
  'ambient+triphop':        'triphop',
  // chillout blends
  'chillout+jazz':          'jazz',
  'chillout+ambient':       'ambient',
  'chillout+electronic':    'electronic',
  'chillout+pop':           'pop',
  'chillout+rnb':           'rnb',
  // newage blends
  'newage+ambient':         'ambient',
  'newage+classical':       'classical',
  'newage+electronic':      'ambient',
  // easylistening blends
  'easylistening+jazz':     'jazz',
  'easylistening+classical':'classical',
  'easylistening+pop':      'pop',
  // psychedelic blends
  'psychedelic+rock':       'psychedelic',
  'psychedelic+electronic': 'electronic',
  'psychedelic+folk':       'folk',
  'psychedelic+ambient':    'ambient',
};

// Blends top-2 moods into a single resolved mood group.
// Key: `${mood1}+${mood2}` — higher-scored mood first.
// Value: a canonical mood word used to form the genre+mood profile key.
// Combos not listed fall back to mood1 (dominant mood).
export const MoodBlendMap: Record<string, string> = {
  // emotional conflicts with upbeat → emotional wins
  'emotional+upbeat':    'emotional',
  'emotional+energetic': 'emotional',
  'emotional+groovy':    'emotional',
  'emotional+summer':    'romantic',
  'emotional+epic':      'epic',
  'emotional+dramatic':  'epic',
  'emotional+dark':      'dark',
  'emotional+ballad':    'emotional',
  'emotional+romantic':  'romantic',
  'emotional+melancholic':'emotional',
  'emotional+calm':      'emotional',
  'emotional+meditative':'calm',
  // dark + X
  'dark+emotional':      'dark',
  'dark+epic':           'dark',
  'dark+heavy':          'dark',
  'dark+upbeat':         'dark',
  'dark+groovy':         'dark',
  'dark+romantic':       'dark',
  'dark+calm':           'dark',
  'dark+meditative':     'dark',
  'dark+dramatic':       'dark',
  // epic + X
  'epic+emotional':      'epic',
  'epic+dark':           'dark',
  'epic+upbeat':         'epic',
  'epic+groovy':         'upbeat',
  'epic+dramatic':       'epic',
  'epic+powerful':       'epic',
  'epic+calm':           'epic',
  'epic+romantic':       'epic',
  // upbeat + X
  'upbeat+emotional':    'emotional',
  'upbeat+dark':         'dark',
  'upbeat+epic':         'upbeat',
  'upbeat+groovy':       'upbeat',
  'upbeat+summer':       'upbeat',
  'upbeat+romantic':     'upbeat',
  'upbeat+calm':         'upbeat',
  'upbeat+dramatic':     'epic',
  // groovy + X
  'groovy+upbeat':       'upbeat',
  'groovy+dark':         'dark',
  'groovy+emotional':    'emotional',
  'groovy+epic':         'upbeat',
  'groovy+summer':       'upbeat',
  'groovy+calm':         'upbeat',
  // calm + X
  'calm+emotional':      'emotional',
  'calm+dark':           'dark',
  'calm+upbeat':         'upbeat',
  'calm+groovy':         'upbeat',
  'calm+epic':           'epic',
  'calm+romantic':       'calm',
  'calm+meditative':     'calm',
  'calm+dream':          'calm',
  // romantic + X
  'romantic+emotional':  'romantic',
  'romantic+dark':       'dark',
  'romantic+upbeat':     'upbeat',
  'romantic+epic':       'epic',
  'romantic+groovy':     'romantic',
  'romantic+calm':       'calm',
  // dramatic (→ epic)
  'dramatic+dark':       'dark',
  'dramatic+emotional':  'epic',
  'dramatic+upbeat':     'epic',
  'dramatic+epic':       'epic',
  // heavy (→ dark or epic)
  'heavy+dark':          'dark',
  'heavy+epic':          'epic',
  'heavy+emotional':     'dark',
  'heavy+upbeat':        'upbeat',
  // summer
  'summer+upbeat':       'upbeat',
  'summer+emotional':    'emotional',
  'summer+dark':         'dark',
  'summer+groovy':       'upbeat',
};

// Mood → strobing intensity multiplier. Values >1 boost strobing, <1 suppress it.
// Missing moods default to 1.0 (neutral).
export const MoodStrobingBoost: Record<string, number> = {
  // strong boost — high-energy, kinetic
  energetic: 1.5, action: 1.5, fast: 1.5, sport: 1.5, party: 1.5,
  // moderate boost — dramatic/powerful
  powerful: 1.3, epic: 1.3, trailer: 1.3, game: 1.3,
  // mild boost — upbeat/driving
  dramatic: 1.2, heavy: 1.2, motivational: 1.2, adventure: 1.2,
  upbeat: 1.1, uplifting: 1.1, groovy: 1.1, fun: 1.1, dance: 1.1,
  // neutral (omitted, fall through to 1.0)
  // summer: 1.0, happy: 1.0, positive: 1.0, inspiring: 1.0, retro: 1.0
  // mild suppress — warm/social but not kinetic
  hopeful: 0.9, funny: 0.9, commercial: 0.9, advertising: 0.9,
  children: 0.85, christmas: 0.85, holiday: 0.85,
  cool: 0.85, sexy: 0.85, romantic: 0.8, love: 0.8,
  // moderate suppress — emotional/reflective
  sad: 0.7, melancholic: 0.7, emotional: 0.7, ballad: 0.7,
  melodic: 0.75, travel: 0.75, nature: 0.75,
  documentary: 0.75, film: 0.7, movie: 0.7,
  // strong suppress — calm/ambient
  calm: 0.5, relaxing: 0.5, soft: 0.5, slow: 0.5,
  background: 0.5, corporate: 0.5, soundscape: 0.45,
  // very strong suppress — meditative/ethereal
  meditative: 0.4, dream: 0.4, deep: 0.4, space: 0.4,
};
