export const TagsToProfileMap: Record<string, Record<string, string>> = {
  blues: {
    'rhythm & blues': 'r&b / soul',
  },
  classical: {
    'opera': 'stage & screen',
  },
  electronic: {
    'ambient': 'ambient / drone',
    'dark ambient': 'ambient / drone',
    'drone': 'ambient / drone',
    'dungeon synth': 'ambient / drone',
    'modern classical': 'classical',
    'musique concrète': 'ambient / drone',
    'new age': 'ambient / drone',
    'neofolk': 'folk, world, & country',
    'disco': 'funk / soul',
    'euro-disco': 'funk / soul',
    'italo-disco': 'funk / soul',
    'nu-disco': 'funk / soul',
    'beatdown': 'hip hop',
    'ghetto': 'hip hop',
    'grime': 'hip hop',
    'halftime': 'hip hop',
    'hip hop': 'hip hop',
    'hip-house': 'hip hop',
    'house': 'house / techno / trance',
    'techno': 'house / techno / trance',
    'trance': 'house / techno / trance',
    'tech house': 'house / techno / trance',
    'deep house': 'house / techno / trance',
    'progressive house': 'house / techno / trance',
    'eurodance': 'house / techno / trance',
    'trip hop': 'hip hop',
    'acid jazz': 'jazz',
    'chillwave': 'jazz',
    'downtempo': 'jazz',
    'future jazz': 'jazz',
    'jazzdance': 'jazz',
    'latin': 'latin',
    'tropical house': 'latin',
    'dance-pop': 'pop',
    'disco polo': 'pop',
    'new wave': 'pop',
    'synth-pop': 'pop',
    'dub': 'reggae',
    'breakcore': 'rock',
    'darkwave': 'rock',
    'ebm': 'rock',
    'gabber': 'house / techno / trance',
    'hard techno': 'house / techno / trance',
    'hardcore': 'rock',
    'hardstyle': 'house / techno / trance',
    'industrial': 'rock',
    'noise': 'rock',
    'power electronics': 'rock',
    'rhythmic noise': 'rock',
    'speedcore': 'rock',
  },
  'folk, world, & country': {
    'indian classical': 'classical',
    'country': 'country',
    'bluegrass': 'country',
    'gospel': 'funk / soul',
    'highlife': 'funk / soul',
    'soukous': 'funk / soul',
    'klezmer': 'jazz',
    'flamenco': 'latin',
    'zouk': 'latin',
  },
  'funk / soul': {
    'rhythm & blues': 'r&b / soul',
    'soul': 'r&b / soul',
    'neo soul': 'r&b / soul',
    'psychedelic': 'rock',
  },
  'hip hop': {
    'electro': 'electronic',
    'grime': 'electronic',
    'trip hop': 'electronic',
    'rnb/swing': 'r&b / soul',
    'jazzy hip-hop': 'jazz',
    'pop rap': 'pop',
    'ragga hiphop': 'reggae',
  },
  jazz: {
    'afrobeat': 'funk / soul',
    'jazz-funk': 'funk / soul',
    'soul-jazz': 'funk / soul',
    'afro-cuban jazz': 'latin',
    'bossa nova': 'latin',
    'latin jazz': 'latin',
    'jazz-rock': 'rock',
  },
  latin: {
    'mariachi': 'folk, world, & country',
    'nueva cancion': 'folk, world, & country',
    'ranchera': 'folk, world, & country',
    'tejano': 'folk, world, & country',
    'reggaeton': 'hip hop',
  },
  pop: {
    'chanson': 'jazz',
    'bollywood': 'latin',
    'j-pop': 'k-pop / j-pop',
    'k-pop': 'k-pop / j-pop',
    'music hall': 'stage & screen',
  },
  reggae: {
    'soca': 'latin',
  },
  rock: {
    'atmospheric black metal': 'metal',
    'black metal': 'metal',
    'death metal': 'metal',
    'deathcore': 'metal',
    'doom metal': 'metal',
    'folk metal': 'metal',
    'funeral doom metal': 'metal',
    'goregrind': 'metal',
    'gothic metal': 'metal',
    'grindcore': 'metal',
    'heavy metal': 'metal',
    'melodic death metal': 'metal',
    'metalcore': 'metal',
    'power metal': 'metal',
    'progressive metal': 'metal',
    'speed metal': 'metal',
    'sludge metal': 'metal',
    'technical death metal': 'metal',
    'thrash': 'metal',
    'viking metal': 'metal',
    'krautrock': 'electronic',
    'post rock': 'electronic',
    'space rock': 'electronic',
    'acoustic': 'folk, world, & country',
    'country rock': 'country',
    'folk rock': 'folk, world, & country',
    'neofolk': 'folk, world, & country',
    'funk metal': 'funk / soul',
    'lo-fi': 'jazz',
    'lounge': 'jazz',
    'blues rock': 'blues',
    'brit pop': 'pop',
    'doo wop': 'pop',
    'dream pop': 'pop',
    'new wave': 'pop',
    'parody': 'pop',
    'pop rock': 'pop',
    'power pop': 'pop',
    'soft rock': 'pop',
    'twist': 'pop',
    'yé-yé': 'pop',
    'ska': 'reggae',
  },
  'stage & screen': {
    'score': 'classical',
  },
};

export const GroupTagToProfileMap: Record<string, string> = {
  "children's": 'pop',
  'non-music': 'default',
};