// MTG Jamendo genre tags → base profile (87 classes, flat lowercase)
export const GenreTagToProfileMap: Record<string, string> = {
  // ambient
  'ambient':          'ambient',
  'darkambient':      'ambient',
  'atmospheric':      'ambient',
  'downtempo':        'ambient',
  'soundscape':       'ambient',
  // new age
  'newage':           'new age',
  // blues
  'blues':            'blues',
  'bluesrock':        'blues',
  // chill
  'chillout':         'chill',
  'lounge':           'chill',
  'easylistening':    'easy listening',
  // classical
  'classical':        'classical',
  'orchestral':       'classical',
  'symphonic':        'classical',
  'medieval':         'classical',
  'choir':            'classical',
  // country
  'country':          'country',
  // dance
  'dance':            'dance',
  'eurodance':        'dance',
  'edm':              'dance',
  'club':             'dance',
  'electropop':       'dance',
  'synthpop':         'dance',
  // electronic
  'electronic':       'electronic',
  'electronica':      'electronic',
  'techno':           'electronic',
  'trance':           'electronic',
  'drumnbass':        'electronic',
  'dubstep':          'electronic',
  'breakbeat':        'electronic',
  'idm':              'electronic',
  'minimal':          'electronic',
  'darkwave':         'electronic',
  'newwave':          'electronic',
  'industrial':       'electronic',
  // folk
  'folk':             'folk',
  'celtic':           'folk',
  'ethno':            'folk',
  'world':            'folk',
  'worldfusion':      'folk',
  'singersongwriter': 'folk',
  // disco
  'disco':            'disco',
  // funk
  'funk':             'funk',
  'groove':           'funk',
  // hip-hop
  'hiphop':           'hip-hop',
  'rap':              'hip-hop',
  'triphop':          'trip-hop',
  // house
  'house':            'house',
  'deephouse':        'house',
  // jazz
  'jazz':             'jazz',
  'jazzfusion':       'jazz',
  'acidjazz':         'jazz',
  'swing':            'jazz',
  'bossanova':        'jazz',
  'fusion':           'jazz',
  'improvisation':    'jazz',
  // latin
  'latin':            'latin',
  // metal
  'metal':            'metal',
  // hard rock
  'hardrock':         'hard rock',
  'hard':             'hard rock',
  'grunge':           'hard rock',
  'punkrock':         'hard rock',
  'postrock':         'hard rock',
  'progressive':      'hard rock',
  // psychedelic
  'psychedelic':      'psychedelic',
  // pop
  'pop':              'pop',
  'popfolk':          'pop',
  'instrumentalpop':  'pop',
  'chanson':          'pop',
  // r&b
  'rnb':              'r&b',
  'soul':             'r&b',
  // reggae
  'reggae':           'reggae',
  'dub':              'reggae',
  // rock
  'rock':             'rock',
  'poprock':          'rock',
  'classicrock':      'rock',
  'rocknroll':        'rock',
  'alternative':      'rock',
  'alternativerock':  'rock',
  'indie':            'rock',
  'instrumentalrock': 'rock',
  '60s':              'rock',
  '70s':              'rock',
  '80s':              'pop',
  '90s':              'rock',
  // soundtrack
  'soundtrack':       'ambient',
};

// genre+mood combination overrides.
// Key: `${baseProfile}+${moodTag}` — mood must score above MOOD_OVERRIDE_THRESHOLD.
// Wildcard key: `*+${moodTag}` — applies regardless of genre when mood is very strong.
export const ProfileMoodOverrideMap: Record<string, string> = {
  // rock + mood
  'rock+emotional':       'beautiful',
  'rock+ballad':          'beautiful',
  'rock+melancholic':     'beautiful',
  'rock+dramatic':        'hard rock',
  'rock+heavy':           'hard rock',
  'rock+powerful':        'hard rock',
  'rock+epic':            'hard rock',
  'rock+upbeat':          'dance',
  'rock+groovy':          'funk',
  'rock+retro':           'rock',
  'rock+cool':            'rock',
  'rock+meditative':      'folk',
  'rock+nature':          'folk',
  'rock+romantic':        'beautiful',
  'rock+love':            'beautiful',
  // pop + mood
  'pop+emotional':        'beautiful',
  'pop+ballad':           'beautiful',
  'pop+dramatic':         'dance',
  'pop+epic':             'dance',
  'pop+heavy':            'hard rock',
  'pop+retro':            'disco',
  'pop+cool':             'r&b',
  'pop+summer':           'dance',
  'pop+holiday':          'happy',
  'pop+children':         'happy',
  'pop+advertising':      'pop',
  'pop+commercial':       'pop',
  'pop+uplifting':        'happy',
  'pop+inspiring':        'happy',
  // electronic + mood
  'electronic+emotional': 'trip-hop',
  'electronic+ballad':    'ambient',
  'electronic+dramatic':  'energetic',
  'electronic+epic':      'energetic',
  'electronic+heavy':     'metal',
  'electronic+powerful':  'energetic',
  'electronic+retro':     'disco',
  'electronic+adventure': 'energetic',
  'electronic+trailer':   'energetic',
  'electronic+game':      'energetic',
  'electronic+space':     'ambient',
  'electronic+dream':     'ambient',
  'electronic+nature':    'ambient',
  'electronic+film':      'ambient',
  'electronic+movie':     'ambient',
  'electronic+summer':    'dance',
  // hip-hop + mood
  'hip-hop+emotional':    'trip-hop',
  'hip-hop+ballad':       'r&b',
  'hip-hop+dramatic':     'hip-hop',
  'hip-hop+epic':         'hip-hop',
  'hip-hop+heavy':        'metal',
  'hip-hop+powerful':     'hip-hop',
  'hip-hop+retro':        'funk',
  'hip-hop+groovy':       'funk',
  'hip-hop+cool':         'hip-hop',
  'hip-hop+upbeat':       'dance',
  'hip-hop+summer':       'dance',
  // r&b + mood
  'r&b+emotional':        'beautiful',
  'r&b+ballad':           'beautiful',
  'r&b+dramatic':         'r&b',
  'r&b+calm':             'mellow',
  'r&b+soft':             'mellow',
  'r&b+cool':             'r&b',
  'r&b+retro':            'funk',
  'r&b+upbeat':           'funk',
  'r&b+summer':           'funk',
  // jazz + mood
  'jazz+emotional':       'beautiful',
  'jazz+ballad':          'beautiful',
  'jazz+dramatic':        'jazz',
  'jazz+epic':            'jazz',
  'jazz+retro':           'jazz',
  'jazz+cool':            'chill',
  'jazz+meditative':      'chill',
  'jazz+nature':          'ambient',
  'jazz+space':           'ambient',
  // blues + mood
  'blues+emotional':      'sad',
  'blues+ballad':         'sad',
  'blues+dramatic':       'blues',
  'blues+heavy':          'hard rock',
  'blues+groovy':         'funk',
  'blues+retro':          'blues',
  'blues+cool':           'blues',
  // folk + mood
  'folk+emotional':       'beautiful',
  'folk+ballad':          'beautiful',
  'folk+dramatic':        'beautiful',
  'folk+upbeat':          'rock',
  'folk+groovy':          'funk',
  'folk+retro':           'folk',
  'folk+nature':          'folk',
  'folk+travel':          'folk',
  'folk+summer':          'folk',
  // ambient + mood
  'ambient+emotional':    'beautiful',
  'ambient+dramatic':     'electronic',
  'ambient+epic':         'electronic',
  'ambient+adventure':    'electronic',
  'ambient+nature':       'ambient',
  'ambient+space':        'ambient',
  'ambient+dream':        'ambient',
  'ambient+meditative':   'ambient',
  'ambient+film':         'ambient',
  'ambient+movie':        'ambient',
  'ambient+travel':       'ambient',
  // hard rock + mood
  'hard rock+emotional':  'beautiful',
  'hard rock+ballad':     'rock',
  'hard rock+epic':       'energetic',
  'hard rock+dramatic':   'energetic',
  'hard rock+powerful':   'energetic',
  'hard rock+groovy':     'funk',
  'hard rock+retro':      'rock',
  // metal + mood
  'metal+emotional':      'hard rock',
  'metal+epic':           'metal',
  'metal+dramatic':       'metal',
  'metal+powerful':       'metal',
  'metal+heavy':          'metal',
  // disco + mood
  'disco+groovy':         'disco',
  'disco+retro':          'disco',
  'disco+summer':         'dance',
  'disco+upbeat':         'dance',
  'disco+cool':           'r&b',
  // trip-hop + mood
  'trip-hop+emotional':   'sad',
  'trip-hop+ballad':      'beautiful',
  'trip-hop+dramatic':    'trip-hop',
  'trip-hop+dark':        'trip-hop',
  'trip-hop+deep':        'ambient',
  'trip-hop+dream':       'ambient',
  // psychedelic + mood
  'psychedelic+emotional':'beautiful',
  'psychedelic+epic':     'energetic',
  'psychedelic+dramatic': 'hard rock',
  'psychedelic+calm':     'ambient',
  'psychedelic+nature':   'ambient',
  'psychedelic+dream':    'ambient',
  // new age + mood
  'new age+emotional':    'beautiful',
  'new age+dramatic':     'ambient',
  'new age+nature':       'ambient',
  'new age+space':        'ambient',
  'new age+meditative':   'ambient',
  'new age+dream':        'ambient',
  // chill + mood
  'chill+emotional':      'beautiful',
  'chill+ballad':         'beautiful',
  'chill+retro':          'mellow',
  'chill+groovy':         'funk',
  'chill+summer':         'mellow',
  // mellow + mood
  'mellow+energetic':     'dance',
  'mellow+dramatic':      'rock',
  'mellow+groovy':        'funk',
  'mellow+retro':         'mellow',
  // country + mood
  'country+energetic':    'rock',
  'country+sad':          'sad',
  'country+emotional':    'beautiful',
  'country+retro':        'country',
  'country+summer':       'folk',
  // latin + mood
  'latin+energetic':      'dance',
  'latin+groovy':         'funk',
  'latin+romantic':       'sexy',
  'latin+sexy':           'sexy',
  'latin+dramatic':       'latin',
  'latin+epic':           'latin',
  // reggae + mood
  'reggae+energetic':     'dance',
  'reggae+groovy':        'funk',
  'reggae+summer':        'reggae',
  'reggae+retro':         'reggae',
  // classical + mood
  'classical+emotional':  'beautiful',
  'classical+dramatic':   'classical',
  'classical+epic':       'classical',
  'classical+calm':       'ambient',
  'classical+meditative': 'ambient',
  // house + mood
  'house+dark':           'electronic',
  'house+emotional':      'trip-hop',
  'house+epic':           'energetic',
  'house+dramatic':       'energetic',
  // energetic + mood
  'energetic+dark':       'metal',
  'energetic+dramatic':   'energetic',
  'energetic+groovy':     'dance',
  // universal strong-mood overrides (wildcard, require MOOD_WILDCARD_THRESHOLD)
  // only truly cross-genre moods live here
  '*+sexy':               'sexy',
  '*+sad':                'sad',
  '*+happy':              'happy',
  '*+party':              'house',
};

// Minimum mood score to trigger an override
export const MOOD_OVERRIDE_THRESHOLD = 0.5;

// Minimum mood score for wildcard (*) overrides — higher bar
export const MOOD_WILDCARD_THRESHOLD = 0.65;
