services:
  analyzer:
    image: prismabeam-analyzer
    build: ./analyzer
  prismabeam:
    image: prismabeam
    build: .
    depends_on:
      analyzer:
        condition: service_healthy
    environment:
      ANALYZER_HOST: analyzer
