services:
  analyzer:
    image: prismabeam-analyzer
    build: ./analyzer
    ports:
      - 7441:7441/udp
  prismabeam:
    image: prismabeam
    build: .
    depends_on:
      analyzer:
        condition: service_healthy
    environment:
      ANALYZER_HOST: analyzer
    ports:
      - 7400:7400
