allowBuilds:
  '@serialport/bindings-cpp': true
  '@tensorflow/tfjs-node': true
  core-js: true
  koffi: true

onlyBuiltDependencies:
  - '@serialport/bindings-cpp'
  - '@tensorflow/tfjs-node'
  - core-js
  - koffi

allowedDeprecatedVersions:
  are-we-there-yet: "*"
  npmlog: "*"
  gauge: "*"
  glob: "*"
  inflight: "*"
  rimraf: "*"
  tar: "*"
