packages:
  - .
  - ui

allowBuilds:
  '@serialport/bindings-cpp': true
  '@tensorflow/tfjs-node': true
  core-js: true
  esbuild: true
  koffi: true

allowedDeprecatedVersions:
  are-we-there-yet: "*"
  gauge: "*"
  glob: "*"
  inflight: "*"
  npmlog: "*"
  rimraf: "*"
  tar: "*"

ignoreWorkspaceRootCheck: true

onlyBuiltDependencies:
  - '@serialport/bindings-cpp'
  - '@tensorflow/tfjs-node'
  - core-js
  - esbuild
  - koffi